name: Integration Pipeline

on:
  push:
    branches: '**'
  pull_request:
    branches: 'master'

jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Assemble
        run: ./gradlew assembleDebug