name: Integration Pipeline

on:
  push:
    branches-ignore: ['release/**']
  pull_request:
    branches: ['master']

jobs:

  setup_environment:
    uses: ./.github/workflows/setup-steps.yml

  integrate:
    needs: setup_environment
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/integration-steps.yml