name: Integration Pipeline

on:
  push:
    branches: '**'
  pull_request:
    branches: 'master'

jobs:
  integrate:
    runs-on: macos-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java distribution
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add permissions for Gradle
        run: chmod +x gradlew

      - name: Assemble
        run: ./gradlew assembleDebug

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          script: ./gradlew connectedDebugAndroidTest

      - name: Test Results Upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: app/build/**/TEST-*.xml

      - name: Test Results Presentation
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: app/build/**/TEST-*.xml


