name: Integration Pipeline

on:
  push:
    branches: '**'
  pull_request:
    branches: 'master'

jobs:
  integrate:
    runs-on: macos-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java distribution
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add permissions for Gradle
        run: chmod +x gradlew

      - name: Assemble
        run: ./gradlew assembleDebug

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          script: ./gradlew connectedDebugAndroidTest

      - name: Test Results Upload
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/**/TEST-*.html

      - name: Test Results Presentation
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Test Results
          path: '*.xml'
          reporter: java-junit


